//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akcesoria
    {
        public int IdAkcesoria { get; set; }
        public string NazwaOpis { get; set; }
        public double Cena { get; set; }
        public Nullable<int> Wypozyczenie_IdWypozyczenie { get; set; }
    
        public virtual Wypozyczenie Wypozyczenie { get; set; }
    }
}
