//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DowodRejestracyjny
    {
        public int DowodRejId { get; set; }
        public string VIN { get; set; }
        public int Seria { get; set; }
        public string NrRejestracyjny { get; set; }
        public int SamochodId { get; set; }
    
        public virtual Samochod Samochod { get; set; }
    }
}
