//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DowodOsobisty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DowodOsobisty()
        {
            this.ImageDowodOsobisty = new HashSet<ImageDowodOsobisty>();
        }
    
        public int DowodOsobistyId { get; set; }
        public int PESEL { get; set; }
        public string NrDowodu { get; set; }
        public System.DateTime TerminWaznosci { get; set; }
        public int OsobaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageDowodOsobisty> ImageDowodOsobisty { get; set; }
        public virtual Osoba Osoba { get; set; }
    }
}
