//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        public int IdKlient { get; set; }
        public int Osoba_IdOsoba { get; set; }
    
        public virtual Osoba Osoba { get; set; }
        public virtual KlientFirma KlientFirma { get; set; }
        public virtual KlientIndywidualny KlientIndywidualny { get; set; }
    }
}
