//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlientIndywidualny
    {
        public int IdKlient { get; set; }
        public int IdKlientIndywidualny { get; set; }
        public int PrawoJazdy_IdPrawaJazdy { get; set; }
        public Nullable<int> RabatInd { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
