//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Osoba()
        {
            this.Klients = new HashSet<Klient>();
            this.Pracowniks = new HashSet<Pracownik>();
        }
    
        public int IdOsoba { get; set; }
        public string ImieNazwisko { get; set; }
        public System.DateTime DataUrodzenia { get; set; }
        public string Adres { get; set; }
        public string KodPocztowy { get; set; }
        public string Kraj { get; set; }
        public string NrTelefonu { get; set; }
        public int Uzytkownik_IdUzytkownik { get; set; }
        public string Miasto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klient> Klients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pracownik> Pracowniks { get; set; }
    }
}
