//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paszport
    {
        public int PaszportId { get; set; }
        public string NrPaszportu { get; set; }
        public Nullable<System.DateTime> TerminWaznosci { get; set; }
        public int OsobaId { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
