//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paszport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paszport()
        {
            this.ImagePaszport = new HashSet<ImagePaszport>();
        }
    
        public int PaszportId { get; set; }
        public string NrPaszportu { get; set; }
        public Nullable<System.DateTime> TerminWaznosci { get; set; }
        public int OsobaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagePaszport> ImagePaszport { get; set; }
        public virtual Osoba Osoba { get; set; }
    }
}
