//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracownikWypozyczenie
    {
        public int PracownikWypozyczenieId { get; set; }
        public int PracownikId { get; set; }
        public int WypozyczenieId { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual Wypozyczenie Wypozyczenie { get; set; }
    }
}
