//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int IdPracownik { get; set; }
        public System.DateTime DataZatrudnienia { get; set; }
        public Nullable<System.DateTime> DataZwolnienia { get; set; }
        public double Pensja { get; set; }
        public Nullable<double> Premia { get; set; }
        public string Stanowisko { get; set; }
        public int Osoba_IdOsoba { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
