//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrawoJazdy
    {
        public int PrawoJazdyId { get; set; }
        public string NrPrawaJazdy { get; set; }
        public string KrajWydania { get; set; }
        public string Kategoria { get; set; }
        public int OsobaId { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
