//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przeglad
    {
        public int PrzegladId { get; set; }
        public System.DateTime DataPrzegladu { get; set; }
        public System.DateTime DataKolejnegoPrzegladu { get; set; }
        public string Uwagi { get; set; }
        public int SamochodId { get; set; }
    
        public virtual Samochod Samochod { get; set; }
    }
}
