//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozliczenie
    {
        public int RozliczenieId { get; set; }
        public Nullable<double> DodatkoweOplaty { get; set; }
        public double Zaliczka { get; set; }
        public Nullable<double> DodatkowyRabat { get; set; }
        public double CalkowityKoszt { get; set; }
        public int WypozyczenieId { get; set; }
    
        public virtual Wypozyczenie Wypozyczenie { get; set; }
    }
}
