//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochod()
        {
            this.Cenniks = new HashSet<Cennik>();
            this.Dostepnoscs = new HashSet<Dostepnosc>();
            this.Opis = new HashSet<Opis>();
            this.Przeglads = new HashSet<Przeglad>();
            this.Serwis = new HashSet<Serwis>();
            this.Ubezpieczenies = new HashSet<Ubezpieczenie>();
            this.Wypozyczenies = new HashSet<Wypozyczenie>();
        }
    
        public int IdSamochodu { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Wersja { get; set; }
        public System.DateTime RokProdukcji { get; set; }
        public string RodzajSilnika { get; set; }
        public string PojemnoscSilnika { get; set; }
        public string SkrzyniaBiegow { get; set; }
        public string LiczbaDrzwi { get; set; }
        public string Kolor { get; set; }
        public int DowodRejestracyjny_IdDowodRej { get; set; }
        public int Cennik_IdCennik { get; set; }
        public int Przebieg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cennik> Cenniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostepnosc> Dostepnoscs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opis> Opis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przeglad> Przeglads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serwis> Serwis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ubezpieczenie> Ubezpieczenies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenie> Wypozyczenies { get; set; }
    }
}
