//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubezpieczenie
    {
        public int UbezpieczenieId { get; set; }
        public string NumerPolisy { get; set; }
        public System.DateTime WazneOd { get; set; }
        public System.DateTime WazneDo { get; set; }
        public int SamochodId { get; set; }
    
        public virtual Samochod Samochod { get; set; }
    }
}
