//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenie()
        {
            this.Akcesoria = new HashSet<Akcesoria>();
            this.PracownikWypozyczenie = new HashSet<PracownikWypozyczenie>();
            this.Rozliczenie = new HashSet<Rozliczenie>();
            this.WypSam = new HashSet<WypSam>();
        }
    
        public int WypozyczenieId { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public System.DateTime DataZwrotu { get; set; }
        public bool CzyDostarczany { get; set; }
        public bool CzyKierowca { get; set; }
        public string AdresDojazdu { get; set; }
        public int WydarzenieId { get; set; }
        public int OsobaId { get; set; }
        public string Uwagi { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akcesoria> Akcesoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PracownikWypozyczenie> PracownikWypozyczenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozliczenie> Rozliczenie { get; set; }
        public virtual Wydarzenie Wydarzenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypSam> WypSam { get; set; }
        public virtual Osoba Osoba { get; set; }
    }
}
