//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WypozyczenieEntities : DbContext
    {
        public WypozyczenieEntities()
            : base("name=WypozyczenieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akcesoria> Akcesoria { get; set; }
        public virtual DbSet<Cennik> Cennik { get; set; }
        public virtual DbSet<Dostepnosc> Dostepnosc { get; set; }
        public virtual DbSet<DowodOsobisty> DowodOsobisty { get; set; }
        public virtual DbSet<DowodRejestracyjny> DowodRejestracyjny { get; set; }
        public virtual DbSet<KlientFirma> KlientFirma { get; set; }
        public virtual DbSet<KlientIndywidualny> KlientIndywidualny { get; set; }
        public virtual DbSet<Opis> Opis { get; set; }
        public virtual DbSet<Osoba> Osoba { get; set; }
        public virtual DbSet<Paszport> Paszport { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<PracownikWypozyczenie> PracownikWypozyczenie { get; set; }
        public virtual DbSet<PrawoJazdy> PrawoJazdy { get; set; }
        public virtual DbSet<Przeglad> Przeglad { get; set; }
        public virtual DbSet<Rozliczenie> Rozliczenie { get; set; }
        public virtual DbSet<Samochod> Samochod { get; set; }
        public virtual DbSet<Serwis> Serwis { get; set; }
        public virtual DbSet<Ubezpieczenie> Ubezpieczenie { get; set; }
        public virtual DbSet<Wydarzenie> Wydarzenie { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenie { get; set; }
        public virtual DbSet<WypSam> WypSam { get; set; }
    }
}
