//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wypozyczenie()
        {
            this.Akcesoria = new HashSet<Akcesoria>();
            this.Rozliczenia = new HashSet<Rozliczenie>();
            this.Samochody = new HashSet<Samochod>();
        }
    
        public int IdWypozyczenie { get; set; }
        public System.DateTime DataWypozyczenia { get; set; }
        public System.DateTime DataZwrotu { get; set; }
        public bool CzyDostarczany { get; set; }
        public bool CzyKierowca { get; set; }
        public int Uzytkownik_IdUzytkownik { get; set; }
        public string AdresDojazdu { get; set; }
        public int Rozliczenie_IdRozliczenie { get; set; }
        public int Wydarzenie_IdWydarzenie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Akcesoria> Akcesoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozliczenie> Rozliczenia { get; set; }
        public virtual Wydarzenie Wydarzenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Samochod> Samochody { get; set; }
    }
}
