//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypożyczalniaSamochodówPremium.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WypozyczalniaEntities : DbContext
    {
        public WypozyczalniaEntities()
            : base("name=WypozyczalniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akcesoria> Akcesorias { get; set; }
        public virtual DbSet<Cennik> Cenniks { get; set; }
        public virtual DbSet<Dostepnosc> Dostepnoscs { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<KlientFirma> KlientFirmas { get; set; }
        public virtual DbSet<KlientIndywidualny> KlientIndywidualnies { get; set; }
        public virtual DbSet<Opis> Opis1 { get; set; }
        public virtual DbSet<Osoba> Osobas { get; set; }
        public virtual DbSet<Pracownik> Pracowniks { get; set; }
        public virtual DbSet<Przeglad> Przeglads { get; set; }
        public virtual DbSet<Rozliczenie> Rozliczenies { get; set; }
        public virtual DbSet<Samochod> Samochods { get; set; }
        public virtual DbSet<Serwis> Serwis1 { get; set; }
        public virtual DbSet<Ubezpieczenie> Ubezpieczenies { get; set; }
        public virtual DbSet<Wydarzenie> Wydarzenies { get; set; }
        public virtual DbSet<Wypozyczenie> Wypozyczenies { get; set; }
    }
}
